import type {
  AnalysisRun,
  Finding,
  ReviewDecision,
  TraceabilityRequirement,
  EvidenceLink,
  ChangedArtifact,
  TestArtifact,
} from './types.js';

export const SAMPLE_RUN: AnalysisRun = {
  id: 'sample-run-fixture',
  name: 'Analysis: sample (Synthetic Checkout)',
  status: 'completed',
  contentFingerprint: '71f88d7a9f57c54b4c1b645198d18fa768c50d93776392a5e1cb17053aa948e4',
  bundleId: 'sample',
  createdAt: '2026-09-27T01:20:00.000Z',
  completedAt: '2026-09-27T01:20:01.250Z',
  summary: {
    totalRequirements: 5,
    totalChangedArtifacts: 5,
    totalTestArtifacts: 12,
    totalEvidenceLinks: 48,
    totalFindings: 5,
    needsHumanReviewCount: 4,
    findingsBySeverity: {
      critical: 0,
      high: 1,
      medium: 3,
      low: 1,
      informational: 0,
    },
    findingsByStatus: {
      verified: 0,
      partial: 0,
      missing_evidence: 1,
      needs_human_review: 4,
      informational: 0,
    },
  },
};

export const SAMPLE_CHANGED_ARTIFACTS: ChangedArtifact[] = [
  {
    id: 'artifact-1',
    filePath: 'src/orders/order.service.ts',
    changeType: 'modified',
    symbols: ['cancelOrder', 'createOrder', 'getOrder'],
    addedLines: 24,
    deletedLines: 6,
    hunks: [],
    isPublicApi: true,
    isConfig: false,
    isSchema: false,
    isTest: false,
    isDocumentation: false,
  },
  {
    id: 'artifact-2',
    filePath: 'src/orders/bulk-import.handler.ts',
    changeType: 'added',
    symbols: ['BulkImportResult', 'RawOrderRow', 'RowError', 'processBulkImport'],
    addedLines: 78,
    deletedLines: 0,
    hunks: [],
    isPublicApi: true,
    isConfig: false,
    isSchema: false,
    isTest: false,
    isDocumentation: false,
  },
  {
    id: 'artifact-3',
    filePath: 'src/export/csv.exporter.ts',
    changeType: 'modified',
    symbols: ['ExportOptions', 'exportOrdersToCsv'],
    addedLines: 32,
    deletedLines: 8,
    hunks: [],
    isPublicApi: true,
    isConfig: false,
    isSchema: false,
    isTest: false,
    isDocumentation: false,
  },
  {
    id: 'artifact-4',
    filePath: 'src/tax/tax.calculator.ts',
    changeType: 'modified',
    symbols: ['TaxRate', 'calculateTax', 'roundCents'],
    addedLines: 18,
    deletedLines: 4,
    hunks: [],
    isPublicApi: false,
    isConfig: false,
    isSchema: false,
    isTest: false,
    isDocumentation: false,
  },
  {
    id: 'artifact-5',
    filePath: 'src/auth/auth.middleware.ts',
    changeType: 'modified',
    symbols: ['ADMIN_ROLE_HEADER', 'AuthContext', 'UserRole', 'requireAdmin'],
    addedLines: 22,
    deletedLines: 5,
    hunks: [],
    isPublicApi: false,
    isConfig: false,
    isSchema: false,
    isTest: false,
    isDocumentation: false,
  },
];

export const SAMPLE_TEST_ARTIFACTS: TestArtifact[] = [
  {
    id: 'test-1',
    filePath: 'tests/orders/order.service.test.ts',
    testName:
      'REQ-001 createOrder > AC-001-1: creates a pending order for valid item and quantity > 0',
    referencedSymbols: ['createOrder'],
    referencedRequirementIds: ['REQ-001'],
  },
  {
    id: 'test-2',
    filePath: 'tests/orders/order.service.test.ts',
    testName: 'REQ-001 createOrder > AC-001-2: throws ItemNotFoundError for unknown item',
    referencedSymbols: ['createOrder'],
    referencedRequirementIds: ['REQ-001'],
  },
  {
    id: 'test-3',
    filePath: 'tests/orders/order.service.test.ts',
    testName: 'REQ-001 createOrder > AC-001-3: throws InvalidQuantityError for quantity <= 0',
    referencedSymbols: ['createOrder'],
    referencedRequirementIds: ['REQ-001'],
  },
  {
    id: 'test-4',
    filePath: 'tests/orders/order.service.test.ts',
    testName: 'REQ-001 createOrder > AC-003-1: cancels a pending order',
    referencedSymbols: ['cancelOrder'],
    referencedRequirementIds: ['REQ-003'],
  },
  {
    id: 'test-5',
    filePath: 'tests/orders/order.service.test.ts',
    testName: 'REQ-001 createOrder > AC-003-2: throws OrderNotCancellableError for fulfilled order',
    referencedSymbols: ['cancelOrder'],
    referencedRequirementIds: ['REQ-003'],
  },
  {
    id: 'test-6',
    filePath: 'tests/export/csv.exporter.test.ts',
    testName: 'REQ-002 exportOrdersToCsv > AC-002-1: excludes cancelled orders by default',
    referencedSymbols: ['exportOrdersToCsv'],
    referencedRequirementIds: ['REQ-002'],
  },
  {
    id: 'test-7',
    filePath: 'tests/export/csv.exporter.test.ts',
    testName:
      'REQ-002 exportOrdersToCsv > AC-002-2: includes cancelled orders when includeCancelled is true',
    referencedSymbols: ['exportOrdersToCsv'],
    referencedRequirementIds: ['REQ-002'],
  },
  {
    id: 'test-8',
    filePath: 'tests/tax/tax.calculator.test.ts',
    testName: 'REQ-004 TaxCalculator > AC-004-1: rounds tax to 2 decimal places',
    referencedSymbols: ['calculateTax', 'roundCents'],
    referencedRequirementIds: ['REQ-004'],
  },
  {
    id: 'test-9',
    filePath: 'tests/tax/tax.calculator.test.ts',
    testName: 'REQ-004 TaxCalculator > AC-004-2: uses the configured jurisdiction rate',
    referencedSymbols: ['calculateTax'],
    referencedRequirementIds: ['REQ-004'],
  },
  {
    id: 'test-10',
    filePath: 'tests/auth/auth.middleware.test.ts',
    testName: 'requireAdmin > does not throw for admin context',
    referencedSymbols: ['requireAdmin'],
    referencedRequirementIds: ['REQ-005'],
  },
  {
    id: 'test-11',
    filePath: 'tests/auth/auth.middleware.test.ts',
    testName: 'requireAdmin > throws 403 for non-admin context',
    referencedSymbols: ['requireAdmin'],
    referencedRequirementIds: ['REQ-005'],
  },
  {
    id: 'test-12',
    filePath: 'tests/auth/auth.middleware.test.ts',
    testName: 'requireAdmin > does not throw for authenticated user',
    referencedSymbols: ['requireAdmin'],
    referencedRequirementIds: ['REQ-005'],
  },
];

export const SAMPLE_FINDINGS: Finding[] = [
  {
    id: 'finding-000001',
    ruleId: 'PUBLIC_API_CHANGED',
    severity: 'medium',
    status: 'needs_human_review',
    title: 'Public API changed: src/orders/order.service.ts',
    explanation:
      'The file "src/orders/order.service.ts" contains exported symbols [cancelOrder, createOrder, getOrder] that were modified. Public API changes may introduce breaking changes to callers.',
    requirementIds: ['REQ-001', 'REQ-003', 'REQ-005'],
    changedArtifactIds: ['artifact-1'],
    testArtifactIds: [],
    evidenceLinkIds: ['link-000001', 'link-000005', 'link-000008'],
    matchStrength: 'moderate',
    recommendedAction:
      'Review the public API signature in "src/orders/order.service.ts". Update documentation and verify callers if necessary.',
  },
  {
    id: 'finding-000002',
    ruleId: 'PUBLIC_API_CHANGED',
    severity: 'medium',
    status: 'needs_human_review',
    title: 'Public API changed: src/orders/bulk-import.handler.ts',
    explanation:
      'The file "src/orders/bulk-import.handler.ts" introduces new exported symbols [BulkImportResult, RawOrderRow, RowError, processBulkImport].',
    requirementIds: ['REQ-001', 'REQ-002', 'REQ-003', 'REQ-005'],
    changedArtifactIds: ['artifact-2'],
    testArtifactIds: [],
    evidenceLinkIds: ['link-000002', 'link-000003', 'link-000006', 'link-000009'],
    matchStrength: 'moderate',
    recommendedAction:
      'Review the public API additions in "src/orders/bulk-import.handler.ts". Confirm interface stability.',
  },
  {
    id: 'finding-000003',
    ruleId: 'PUBLIC_API_CHANGED',
    severity: 'medium',
    status: 'needs_human_review',
    title: 'Public API changed: src/export/csv.exporter.ts',
    explanation:
      'The file "src/export/csv.exporter.ts" contains exported symbols [ExportOptions, exportOrdersToCsv] that were modified with includeCancelled parameter.',
    requirementIds: ['REQ-002'],
    changedArtifactIds: ['artifact-3'],
    testArtifactIds: [],
    evidenceLinkIds: ['link-000004'],
    matchStrength: 'moderate',
    recommendedAction:
      'Review the public API options in "src/export/csv.exporter.ts". Ensure backward compatibility for default callers.',
  },
  {
    id: 'finding-000004',
    ruleId: 'TEST_GAP_ON_CHANGED_SYMBOL',
    severity: 'high',
    status: 'missing_evidence',
    title: 'Changed symbols in src/orders/bulk-import.handler.ts have no test coverage',
    explanation:
      'Symbols [BulkImportResult, RawOrderRow, RowError, processBulkImport] in "src/orders/bulk-import.handler.ts" were added but no test file exercises them. Uncovered batch ingestion logic poses a regression risk.',
    requirementIds: [],
    changedArtifactIds: ['artifact-2'],
    testArtifactIds: [],
    evidenceLinkIds: [],
    matchStrength: 'none',
    recommendedAction:
      'Add tests covering: BulkImportResult, RawOrderRow, RowError, and error reporting for malformed rows in "src/orders/bulk-import.handler.ts".',
  },
  {
    id: 'finding-000005',
    ruleId: 'DOC_STALE_OR_MISSING',
    severity: 'low',
    status: 'needs_human_review',
    title: 'Changed symbols in src/auth/auth.middleware.ts may not be documented',
    explanation:
      'Symbols [ADMIN_ROLE_HEADER, AuthContext, UserRole] changed in "src/auth/auth.middleware.ts" do not appear in any documentation file.',
    requirementIds: ['REQ-005'],
    changedArtifactIds: ['artifact-5'],
    testArtifactIds: [],
    evidenceLinkIds: [],
    matchStrength: 'weak',
    recommendedAction:
      'Review documentation for "src/auth/auth.middleware.ts" and update docs/api.md or architecture guides as needed.',
  },
];

export const SAMPLE_DECISIONS: ReviewDecision[] = [];

export const SAMPLE_TRACEABILITY: TraceabilityRequirement[] = [
  {
    id: 'REQ-001',
    title: 'Create an order only when the item exists and quantity is greater than zero.',
    body: 'The OrderService must validate item existence and strictly enforce positive quantities before persisting a pending order.',
    acceptanceCriteria: [
      {
        id: 'AC-001-1',
        requirementId: 'REQ-001',
        text: 'Creates pending order for valid item and quantity > 0',
      },
      {
        id: 'AC-001-2',
        requirementId: 'REQ-001',
        text: 'Throws ItemNotFoundError for unknown item',
      },
      {
        id: 'AC-001-3',
        requirementId: 'REQ-001',
        text: 'Throws InvalidQuantityError for quantity <= 0',
      },
    ],
    tags: ['orders', 'validation'],
    linkedCodeArtifacts: [
      {
        id: 'artifact-1',
        filePath: 'src/orders/order.service.ts',
        symbols: ['createOrder', 'getOrder'],
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    linkedTestArtifacts: [
      {
        id: 'test-1',
        filePath: 'tests/orders/order.service.test.ts',
        testName:
          'REQ-001 createOrder > AC-001-1: creates a pending order for valid item and quantity > 0',
        strength: 'strong',
        method: 'explicit_req_id',
      },
      {
        id: 'test-2',
        filePath: 'tests/orders/order.service.test.ts',
        testName: 'REQ-001 createOrder > AC-001-2: throws ItemNotFoundError for unknown item',
        strength: 'strong',
        method: 'explicit_req_id',
      },
      {
        id: 'test-3',
        filePath: 'tests/orders/order.service.test.ts',
        testName: 'REQ-001 createOrder > AC-001-3: throws InvalidQuantityError for quantity <= 0',
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    status: 'verified',
  },
  {
    id: 'REQ-002',
    title: 'Export orders to CSV with a documented includeCancelled option.',
    body: 'The CSV export service must allow callers to include or exclude cancelled orders via an explicit options flag.',
    acceptanceCriteria: [
      { id: 'AC-002-1', requirementId: 'REQ-002', text: 'Excludes cancelled orders by default' },
      {
        id: 'AC-002-2',
        requirementId: 'REQ-002',
        text: 'Includes cancelled orders when includeCancelled is true',
      },
    ],
    tags: ['export', 'csv'],
    linkedCodeArtifacts: [
      {
        id: 'artifact-3',
        filePath: 'src/export/csv.exporter.ts',
        symbols: ['ExportOptions', 'exportOrdersToCsv'],
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    linkedTestArtifacts: [
      {
        id: 'test-6',
        filePath: 'tests/export/csv.exporter.test.ts',
        testName: 'REQ-002 exportOrdersToCsv > AC-002-1: excludes cancelled orders by default',
        strength: 'strong',
        method: 'explicit_req_id',
      },
      {
        id: 'test-7',
        filePath: 'tests/export/csv.exporter.test.ts',
        testName:
          'REQ-002 exportOrdersToCsv > AC-002-2: includes cancelled orders when includeCancelled is true',
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    status: 'verified',
  },
  {
    id: 'REQ-003',
    title: 'Cancellation is allowed only while an order is pending.',
    body: 'An order in any state other than pending cannot be cancelled and must reject cancellation with OrderNotCancellableError.',
    acceptanceCriteria: [
      { id: 'AC-003-1', requirementId: 'REQ-003', text: 'Cancels a pending order' },
      {
        id: 'AC-003-2',
        requirementId: 'REQ-003',
        text: 'Throws OrderNotCancellableError for fulfilled order',
      },
    ],
    tags: ['orders', 'state-machine'],
    linkedCodeArtifacts: [
      {
        id: 'artifact-1',
        filePath: 'src/orders/order.service.ts',
        symbols: ['cancelOrder'],
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    linkedTestArtifacts: [
      {
        id: 'test-4',
        filePath: 'tests/orders/order.service.test.ts',
        testName: 'REQ-001 createOrder > AC-003-1: cancels a pending order',
        strength: 'strong',
        method: 'explicit_req_id',
      },
      {
        id: 'test-5',
        filePath: 'tests/orders/order.service.test.ts',
        testName:
          'REQ-001 createOrder > AC-003-2: throws OrderNotCancellableError for fulfilled order',
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    status: 'verified',
  },
  {
    id: 'REQ-004',
    title: 'Tax calculation rounds to cents using the documented jurisdiction rule.',
    body: 'The TaxCalculator must apply jurisdiction tax rates and round the calculated tax to two decimal places.',
    acceptanceCriteria: [
      { id: 'AC-004-1', requirementId: 'REQ-004', text: 'Rounds tax to 2 decimal places' },
      { id: 'AC-004-2', requirementId: 'REQ-004', text: 'Uses configured jurisdiction rate' },
    ],
    tags: ['tax', 'pricing'],
    linkedCodeArtifacts: [
      {
        id: 'artifact-4',
        filePath: 'src/tax/tax.calculator.ts',
        symbols: ['calculateTax', 'roundCents'],
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    linkedTestArtifacts: [
      {
        id: 'test-8',
        filePath: 'tests/tax/tax.calculator.test.ts',
        testName: 'REQ-004 TaxCalculator > AC-004-1: rounds tax to 2 decimal places',
        strength: 'strong',
        method: 'explicit_req_id',
      },
      {
        id: 'test-9',
        filePath: 'tests/tax/tax.calculator.test.ts',
        testName: 'REQ-004 TaxCalculator > AC-004-2: uses the configured jurisdiction rate',
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    status: 'verified',
  },
  {
    id: 'REQ-005',
    title: 'Bulk order import is restricted to administrators and reports malformed rows.',
    body: 'Bulk import of CSV orders must enforce administrator access and produce detailed per-row error diagnostics.',
    acceptanceCriteria: [
      { id: 'AC-005-1', requirementId: 'REQ-005', text: 'Enforces requireAdmin authorization' },
      {
        id: 'AC-005-2',
        requirementId: 'REQ-005',
        text: 'Reports RowError diagnostics on invalid lines',
      },
    ],
    tags: ['bulk-import', 'admin', 'auth'],
    linkedCodeArtifacts: [
      {
        id: 'artifact-2',
        filePath: 'src/orders/bulk-import.handler.ts',
        symbols: ['processBulkImport', 'RowError'],
        strength: 'moderate',
        method: 'keyword_overlap',
      },
      {
        id: 'artifact-5',
        filePath: 'src/auth/auth.middleware.ts',
        symbols: ['requireAdmin'],
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    linkedTestArtifacts: [
      {
        id: 'test-10',
        filePath: 'tests/auth/auth.middleware.test.ts',
        testName: 'requireAdmin > does not throw for admin context',
        strength: 'strong',
        method: 'explicit_req_id',
      },
      {
        id: 'test-11',
        filePath: 'tests/auth/auth.middleware.test.ts',
        testName: 'requireAdmin > throws 403 for non-admin context',
        strength: 'strong',
        method: 'explicit_req_id',
      },
    ],
    status: 'partial',
  },
];

export const SAMPLE_EVIDENCE_LINKS: EvidenceLink[] = [
  {
    id: 'link-000001',
    fromType: 'requirement',
    fromId: 'REQ-001',
    toType: 'changed_artifact',
    toId: 'artifact-1',
    method: 'explicit_req_id',
    strength: 'strong',
    explanation: 'Requirement REQ-001 explicitly referenced in src/orders/order.service.ts',
    sourceLocation: { filePath: 'src/orders/order.service.ts', startLine: 1, endLine: 40 },
  },
  {
    id: 'link-000002',
    fromType: 'requirement',
    fromId: 'REQ-002',
    toType: 'changed_artifact',
    toId: 'artifact-3',
    method: 'explicit_req_id',
    strength: 'strong',
    explanation: 'Requirement REQ-002 explicitly referenced in src/export/csv.exporter.ts',
    sourceLocation: { filePath: 'src/export/csv.exporter.ts', startLine: 1, endLine: 50 },
  },
  {
    id: 'link-000003',
    fromType: 'requirement',
    fromId: 'REQ-003',
    toType: 'changed_artifact',
    toId: 'artifact-1',
    method: 'explicit_req_id',
    strength: 'strong',
    explanation: 'Requirement REQ-003 explicitly referenced in src/orders/order.service.ts',
    sourceLocation: { filePath: 'src/orders/order.service.ts', startLine: 45, endLine: 70 },
  },
  {
    id: 'link-000004',
    fromType: 'requirement',
    fromId: 'REQ-004',
    toType: 'changed_artifact',
    toId: 'artifact-4',
    method: 'explicit_req_id',
    strength: 'strong',
    explanation: 'Requirement REQ-004 explicitly referenced in src/tax/tax.calculator.ts',
    sourceLocation: { filePath: 'src/tax/tax.calculator.ts', startLine: 1, endLine: 35 },
  },
  {
    id: 'link-000005',
    fromType: 'requirement',
    fromId: 'REQ-005',
    toType: 'changed_artifact',
    toId: 'artifact-5',
    method: 'explicit_req_id',
    strength: 'strong',
    explanation: 'Requirement REQ-005 explicitly referenced in src/auth/auth.middleware.ts',
    sourceLocation: { filePath: 'src/auth/auth.middleware.ts', startLine: 1, endLine: 30 },
  },
  {
    id: 'link-000006',
    fromType: 'changed_artifact',
    fromId: 'artifact-1',
    toType: 'test_artifact',
    toId: 'test-1',
    method: 'symbol_overlap',
    strength: 'strong',
    explanation: 'Test references createOrder in src/orders/order.service.ts',
    sourceLocation: { filePath: 'tests/orders/order.service.test.ts', startLine: 12, endLine: 25 },
  },
  {
    id: 'link-000007',
    fromType: 'changed_artifact',
    fromId: 'artifact-3',
    toType: 'test_artifact',
    toId: 'test-6',
    method: 'symbol_overlap',
    strength: 'strong',
    explanation: 'Test references exportOrdersToCsv in src/export/csv.exporter.ts',
    sourceLocation: { filePath: 'tests/export/csv.exporter.test.ts', startLine: 15, endLine: 30 },
  },
  {
    id: 'link-000008',
    fromType: 'changed_artifact',
    fromId: 'artifact-4',
    toType: 'test_artifact',
    toId: 'test-8',
    method: 'symbol_overlap',
    strength: 'strong',
    explanation: 'Test references calculateTax in src/tax/tax.calculator.ts',
    sourceLocation: { filePath: 'tests/tax/tax.calculator.test.ts', startLine: 10, endLine: 22 },
  },
];
